name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # environment: develop
    outputs: 
      test3: ${{ steps.step-3.outputs.test3 }}
      test4: ${{ steps.step-4.outputs.test4 }}
    steps:
    - id: step-1
      uses: actions/checkout@v4
    
    - id: step-2
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - id: step-3
      name: java version
      run: echo "test3=hello" >> "$GITHUB_OUTPUT"
      
    - id: step4
      name: maven version
      run: echo "test4=world" >> "$GITHUB_OUTPUT"
      
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
#    environment:
#      name: develop
#      url: https://github.com/zhoubo1832
    steps:        
    - id: deploy-1
      name: java version
      run: |
        echo 'book_id: ' ${{secrets.BOOK_ID}}
        echo 'book_name: ' ${{secrets.BOOK_NAME}}
      
    - id: deploy-2
      name: maven version
      run: |
        echo 'front_color: ' ${{vars.FRONT_COLOR}}
        echo 'back_color: ' ${{vars.BACK_COLOR}}
  
    - id: deploy-3
      env:
        # OUTPUT1: ${{ needs.build.outputs.test3 }}
        # OUTPUT2: ${{ needs.build.outputs.test4 }}
        OUTPUT1: hello
        OUTPUT2: world
      run: echo "$OUTPUT1 $OUTPUT2"
      
