name: try cache
on: 
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10,12,20]
    steps:
      - name: pre action
        run: echo ${{job.status}}
      - name: show context
        run: |
          echo ${{runner.name}}
          echo ${{runner.os}}
          echo ${{runner.arch}}
          echo ${{runner.temp}}
          echo ${{runner.tool_cache}}
          echo ${{runner.debug}}
          echo ${{runner.environment}}
        
          echo ${{github.action}}
          echo ${{github.action_path}}
          echo ${{github.action_ref}}
          echo ${{github.action_repository}}
          echo ${{github.action_status}}
          echo ${{github.actor_id}}
          echo ${{github.api_url}}
          echo ${{github.base_ref}}
          echo ${{github.env}}
          echo ${{github.event}}
          echo ${{github.event_name}}
          echo ${{github.event_path}}
          echo ${{github.graphql_url}}
          echo ${{github.head_ref}}
          echo ${{github.job}}
          echo ${{github.path}}
          echo ${{github.ref}}
          echo ${{github.ref_name}}
          echo ${{github.ref_protected}}
          echo ${{github.ref_type}}
          echo ${{github.repository}}
          echo ${{github.repository_id}}
          echo ${{github.repository_owner}}
          echo ${{github.repository_owner_id}}
          echo ${{github.repositoryurl}}
          echo ${{github.retention_days}}
          echo ${{github.run_id}}
          echo ${{github.run_number}}
          echo ${{github.run_attempt}}
          echo ${{github.secret_source}}
          echo ${{github.server_url}}
          echo ${{github.sha}}
          echo ${{github.token}}
          echo ${{github.triggering_actor}}
          echo ${{github.workflow}}
          echo ${{github.workflow_ref}}
          echo ${{github.workflow_sha}}
          echo ${{github.workspace}}

          echo ${{strategy.fail-fast}}
          echo ${{strategy.job-index}}
          echo ${{strategy.job-total}}
          echo ${{strategy.max-parallel}}
          
      - name: show envs
        run: |
          echo "CI: $CI"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
          echo "GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_ACTOR_ID: $GITHUB_ACTOR_ID"
          echo "GITHUB_API_URL: $GITHUB_API_URL"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_ENV: $GITHUB_ENV"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_GRAPHQL_URL: $GITHUB_GRAPHQL_URL"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_JOB: $GITHUB_JOB"
          echo "GITHUB_OUTPUT: $GITHUB_OUTPUT"
          echo "GITHUB_PATH: $GITHUB_PATH"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_REF_PROTECTED: $GITHUB_REF_PROTECTED"
          echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REPOSITORY_ID: $GITHUB_REPOSITORY_ID"
          echo "GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_ID: $GITHUB_REPOSITORY_OWNER_ID"
          echo "GITHUB_RETENTION_DAYS: $GITHUB_RETENTION_DAYS"
          echo "GITHUB_RUN_ATTEMPT: $GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_STEP_SUMMARY: $GITHUB_STEP_SUMMARY"
          echo "GITHUB_TRIGGERING_ACTOR: $GITHUB_TRIGGERING_ACTOR"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_WORKFLOW_REF: $GITHUB_WORKFLOW_REF"
          echo "GITHUB_WORKFLOW_SHA: $GITHUB_WORKFLOW_SHA"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "RUNNER_ARCH: $RUNNER_ARCH"
          echo "RUNNER_DEBUG: $RUNNER_DEBUG"
          echo "RUNNER_NAME: $RUNNER_NAME"
          echo "RUNNER_OS: $RUNNER_OS"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
          
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: post action
        run: echo ${{job.status}}
